# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ed2140ae18970e2463f4a669481287f1fb425c4ed47c8fa1596d17f16b244b5ea6e0760f09bb1a1d7604ef2d2d6dbd15424283a5ead3108d4f952b66a27da690

test:
  secret_key_base: ac0687b1696109e993ff51b41869e611103f70ff0008ce1ee3b91ee839f54f3c19d2045da4a905f078b48c2dc381f80e553f5d684d4e652ecac6ad0ad0c8ccbf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
